### ISSUE TITLE
Procedures(Single) - There is no related video as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Dr-Patrick-Briggs#20]
![image](https://cloud.githubusercontent.com/assets/18587097/16294394/9b371bba-394a-11e6-97a5-9985704ea093.png)

**Comment by r-pochanakit** [comment]
Asper project scope:
Videos: Related video frames for YouTube URL
  **- Hide video if no YouTube URL is added to procedure**
  - When videos are clicked, will open them in pop-up using Fancy box"
It didn't show elated video because no video link added to procedure
![image](https://cloud.githubusercontent.com/assets/18692070/16476039/882526da-3ead-11e6-8c8b-843f29908a97.png)

**Comment by r-pochanakit** [comment]
This section will display if you add video link on each procedure.
